### ISSUE TITLE
맨 처음 문자가 한글 음절 문자가 아닌 경우 SIGABRT 에러를 뱉음

### ISSUE THREAD

**Issue by xnuk** [sunho/AheuiJIT#16]
코드:
```
ㅇ
반망희
```

- 기대한 결과: `2`를 출력함
- 실제: `terminate called without an active exception`

**Comment by sunho** [comment]
버그제보 감사합니다. 고쳤어요. https://github.com/sunho/AheuiJIT/releases/tag/v1.2.0
